name: Nightly Elon-vs-Trump Stock Predictor

on:
  schedule:
    - cron: '0 18 * * *'  # 6 PM EST daily
  workflow_dispatch:

jobs:
  predict:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install

      - name: Run prediction script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          python main.py

      - name: Setup authentication for committing file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}

      - name: Commit updated prediction history
        run: |
          git add prediction_history.xlsx
          git commit -m "📈 Update prediction history [skip ci]" || echo "No changes to commit"
          git push
