name: Nightly Elon-vs-Trump Stock Predictor

on:
  schedule:
    - cron: '0 18 * * *'  # Runs daily at 6 PM EST
  workflow_dispatch:

permissions:
  contents: write  # Grants write access to the repository contents

jobs:
  predict:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install

      - name: Run prediction script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          python main.py

      - name: Commit and push prediction history
        uses: EndBug/add-and-commit@v9
        with:
          add: 'prediction_history.xlsx'
          message: '📈 Update prediction history [skip ci]'
          default_author: github_actions

