name: Nightly Elon-vs-Trump Stock Predictor

on:
  schedule:
    - cron: '0 18 * * *'  # 6 PM EST daily
  workflow_dispatch:

jobs:
  predict:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install

      - name: Run prediction script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python main.py

      - name: Send SMS notification with Twilio
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TO_PHONE: ${{ secrets.TO_PHONE }}
          FROM_PHONE: ${{ secrets.FROM_PHONE }}
        run: |
          curl -X POST https://api.twilio.com/2010-04-01/Accounts/$TWILIO_ACCOUNT_SID/Messages.json \
          --data-urlencode "To=$TO_PHONE" \
          --data-urlencode "From=$FROM_PHONE" \
          --data-urlencode "Body=Nightly Elon-vs-Trump stock prediction script ran. Check prediction_history.xlsx in the repo." \
          -u $TWILIO_ACCOUNT_SID:$TWILIO_AUTH_TOKEN

