name: Nightly Elon-vs-Trump Stock Predictor

on:
  schedule:
    - cron: '0 1 * * *'  # every day at 9pm EST (1am UTC)
  workflow_dispatch:

jobs:
  predict:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install

      - name: Run prediction script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python main.py

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Nightly Stock Predictions - Elon vs Trump"
          to: mikepresman@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          body: "The nightly script has run. Check the repo or attached Excel file for details."
          attachments: prediction_history.xlsx
